language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t samuelsalomonv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samuelsalomonv/react-test npm test -- --coverage

after_success:
  - docker build -t samuelsalomonv/multi-fibo-client /client
  - docker build -t samuelsalomonv/multi-fibo-nginx /nginx
  - docker build -t samuelsalomonv/multi-fibo-server /server
  - docker build -t samuelsalomonv/multi-fibo-worker /worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"--password-stdin
  # Take those images and push them to docker hub
  - docker push samuelsalomonv/multi-client
  - docker push samuelsalomonv/multi-nginx
  - docker push samuelsalomonv/multi-server
  - docker push samuelsalomonv/multi-worker

